CREATE TABLE [dbo].[STUDENT_COURSE] (
    [CLARION_ID] INT          NOT NULL,
    [TERM]       VARCHAR (50) NOT NULL,
    [SUBJECT]    VARCHAR (50) NOT NULL,
    [CATALOG]    VARCHAR (50) NOT NULL,
    [SECTION]    VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([CLARION_ID] ASC, [TERM] ASC, [SUBJECT] ASC, [CATALOG] ASC, [SECTION] ASC),
	FOREIGN KEY ([CLARION_ID]) REFERENCES dbo.[STUDENT] ([CLARION_ID]),
	FOREIGN KEY ([TERM], [SUBJECT], [CATALOG], [SECTION]) REFERENCES dbo.[COURSE] ([TERM], [SUBJECT], [CATALOG], [SECTION])
);

