CREATE TABLE [dbo].[COURSE] (
    [TERM]       VARCHAR (50) NOT NULL,
    [SUBJECT]    VARCHAR (50) NOT NULL,
    [CATALOG]    VARCHAR (50) NOT NULL,
    [SECTION]    VARCHAR (50) NOT NULL,
    [PROF_EMAIL] VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([TERM] ASC, [SUBJECT] ASC, [CATALOG] ASC, [SECTION] ASC),
    FOREIGN KEY ([PROF_EMAIL]) REFERENCES [dbo].[PROFESSOR] ([PROF_EMAIL])
);


GO
CREATE NONCLUSTERED INDEX [IX_CATALOG]
    ON [dbo].[COURSE]([CATALOG] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SECTION]
    ON [dbo].[COURSE]([SECTION] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SUBJECT]
    ON [dbo].[COURSE]([SUBJECT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_TERM]
    ON [dbo].[COURSE]([TERM] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_EMAIL]
    ON [dbo].[COURSE]([PROF_EMAIL] ASC);

