CREATE TABLE [dbo].[STUDENT_COURSE] (
    [CLARION_ID] INT          NOT NULL,
    [TERM]       INT NOT NULL,
    [SUBJECT]    VARCHAR (50) NOT NULL,
    [CATALOG]    VARCHAR (50) NOT NULL,
    [SECTION]    VARCHAR (50) NOT NULL,
    CONSTRAINT [STUDENT_COURSE_PK] PRIMARY KEY CLUSTERED ([CLARION_ID] ASC, [TERM] ASC, [SUBJECT] ASC, [CATALOG] ASC, [SECTION] ASC),
    CONSTRAINT [STUDENT_COURSE_STUDENT_FK] FOREIGN KEY ([CLARION_ID]) REFERENCES [dbo].[STUDENT] ([CLARION_ID])
);

