CREATE TABLE [dbo].[TUTOR] (
    [TUTOR_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [CLARION_ID] INT          NOT NULL,
    [STATUS]     VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([TUTOR_ID] ASC),
	FOREIGN KEY ([CLARION_ID]) REFERENCES dbo.[STUDENT] ([CLARION_ID])
);

