//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.VISITs = new HashSet<VISIT>();
            this.STUDENTs = new HashSet<STUDENT>();
        }
    
        public string TERM { get; set; }
        public string SUBJECT { get; set; }
        public string CATALOG { get; set; }
        public string SECTION { get; set; }
        public string PROF_EMAIL { get; set; }
    
        public virtual PROFESSOR PROFESSOR { get; set; }
        public virtual ICollection<VISIT> VISITs { get; set; }
        public virtual ICollection<STUDENT> STUDENTs { get; set; }
    }
}
