//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<COURSE> COURSEs { get; set; }
        public DbSet<PROFESSOR> PROFESSORs { get; set; }
        public DbSet<STUDENT> STUDENTs { get; set; }
        public DbSet<TUTOR> TUTORs { get; set; }
        public DbSet<TUTOR_HOUR> TUTOR_HOUR { get; set; }
        public DbSet<VISIT> VISITs { get; set; }
    }
}
