//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public STUDENT()
        {
            this.TUTORs = new HashSet<TUTOR>();
            this.COURSEs = new HashSet<COURSE>();
        }
    
        public int CLARION_ID { get; set; }
        public string TERM { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLE_name { get; set; }
        public string CNET_USERNAME { get; set; }
        public string EAGLEMAIL { get; set; }
        public string CLASS_STANDING { get; set; }
        public string DEGREE_SEEKING { get; set; }
        public string MAJOR_1 { get; set; }
        public string MAJOR_2 { get; set; }
        public string MINOR_1 { get; set; }
        public string MINOR_2 { get; set; }
        public int CREDIT_ATTEMPTED { get; set; }
        public string SEX { get; set; }
        public string HISPANIC { get; set; }
        public string AMER_INDIAN { get; set; }
        public string ASIAN { get; set; }
        public string BLACK { get; set; }
        public string PACIFIC_ISLANDER { get; set; }
        public string WHITE { get; set; }
        public int AGE { get; set; }
        public string CAMPUS { get; set; }
        public string HOUSING { get; set; }
        public string TRANSFER { get; set; }
        public Nullable<int> TRANSFER_CREDIT { get; set; }
        public int NUMBER_OF_VISIT { get; set; }
    
        public virtual ICollection<TUTOR> TUTORs { get; set; }
        public virtual ICollection<COURSE> COURSEs { get; set; }
    }
}
