//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIS411
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTOR_HOUR
    {
        public int TUTOR_ID { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan TIME_IN { get; set; }
        public Nullable<System.TimeSpan> TIME_OUT { get; set; }
        public Nullable<System.TimeSpan> TIME_DIFFERENCE { get; set; }
    
        public virtual TUTOR TUTOR { get; set; }
    }
}
